sudo: required

services:
  - docker

before_install:
  - docker build -t paihari/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run paihari/react-test npm test -- --watchAll=false

after_success:
  - docker build -t paihari/multi-client ./client
  - docker build -t paihari/multi-nginx ./nginx
  - docker build -t paihari/multi-server ./server
  - docker build -t paihari/multi-worker ./worker

#Push the images to hub.docker
