sudo: required

services:
  - docker

before_install:
  - docker build -t paihari/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run paihari/react-test npm test -- --watchAll=false

after_success:
  - docker build -t paihari/multi-client ./client
  - docker build -t paihari/multi-nginx ./nginx
  - docker build -t paihari/multi-server ./server
  - docker build -t paihari/multi-worker ./worker

#Push the images to hub.docker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push paihari/multi-client
  - docker push paihari/multi-nginx
  - docker push paihari/multi-server
  - docker push paihari/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: us-east-1
#  app: multi-docker-ebs
#  env: MultiDockerEbs-env
#  bucket_name: elasticbeanstalk-us-east-1-898024814010
#  bucket_path: docker-multi-1
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY